import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { withProtected } from "../firebase/auth/hook/route";
import Layout from "../layouts/Layout";
import CreateSessionCard from "@/components/CreateSessionCard";
// import useSWR from "swr";
// import fetcher from "@/lib/fetcher";
import { Session } from ".prisma/client";
import useAuth from "../firebase/auth/hook/auth";

function Home() {
  const { user }: any = useAuth();
  const [sessionCard, setSessionCard] = useState(0);
  const [sessions, setSessions] = useState<Session[]>();

  useEffect(() => {
    const fetchSessions = async () => {
      const fetcher = await fetch("/api/db/session/get", {
        method: "POST",
        body: JSON.stringify({ email: user.email }),
        headers: {
          "Content-Type": "application/json",
        },
      });
      const result = await fetcher.json();
      setSessions(result.session);
    };
    fetchSessions();
  }, [user.email]);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className="mb-7">Dashboard</h2>
        <div className="grid w-full gap-5 md:grid-cols-2 lg:grid-cols-4">
          <div className="w-full p-4 bg-white rounded-md">
            <div className="p-3 mb-3 rounded-md bg-gray-50 w-min">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M4 22a8 8 0 1 1 16 0h-2a6 6 0 1 0-12 0H4zm8-9c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4z" />
              </svg>
            </div>
            <h4 className="font-medium">Total Students</h4>
            <h5 className="text-sm text-gray-500">10 days ago</h5>
          </div>
          <div className="w-full p-4 bg-white rounded-md">
            <div className="p-3 mb-3 rounded-md bg-gray-50 w-min">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M14 14.252v2.09A6 6 0 0 0 6 22l-2-.001a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm5.793 8.914l3.535-3.535 1.415 1.414-4.95 4.95-3.536-3.536 1.415-1.414 2.12 2.121z" />
              </svg>
            </div>
            <h4 className="font-medium">Present</h4>
            <h5 className="text-sm text-gray-500">10 days ago</h5>
          </div>
          <div className="w-full p-4 bg-white rounded-md">
            <div className="p-3 mb-3 rounded-md bg-gray-50 w-min">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M14 14.252v2.09A6 6 0 0 0 6 22l-2-.001a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm7 6.586l2.121-2.122 1.415 1.415L20.414 19l2.122 2.121-1.415 1.415L19 20.414l-2.121 2.122-1.415-1.415L17.586 19l-2.122-2.121 1.415-1.415L19 17.586z" />
              </svg>
            </div>
            <h4 className="font-medium">Absent</h4>
            <h5 className="text-sm text-gray-500">10 days ago</h5>
          </div>
          <div className="w-full p-4 bg-white rounded-md">
            <div className="p-3 mb-3 rounded-md bg-gray-50 w-min">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M12 14v2a6 6 0 0 0-6 6H4a8 8 0 0 1 8-8zm0-1c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm8.828 10.071L18 24l-2.828-2.929c-1.563-1.618-1.563-4.24 0-5.858a3.904 3.904 0 0 1 5.656 0c1.563 1.618 1.563 4.24 0 5.858zm-1.438-1.39c.813-.842.813-2.236 0-3.078a1.904 1.904 0 0 0-2.78 0c-.813.842-.813 2.236 0 3.079L18 21.12l1.39-1.44z" />
              </svg>
            </div>
            <h4 className="font-medium">Late Comer</h4>
            <h5 className="text-sm text-gray-500">10 days ago</h5>
          </div>
        </div>
        <div className="w-full mt-10">
          <div className="w-full">
            <div className="flex mb-5">
              <h3 className="w-full font-bold">Session</h3>
            </div>
            <div className="flex mb-10">
              <input
                type="text"
                className="w-full px-4 py-2 mr-4 transition-all duration-200 border rounded-lg hover:bg-gray-100 focus:bg-gray-100"
                placeholder="Search"
              />
              <button
                onClick={() => setSessionCard(1)}
                className="px-4 py-2 text-white transition-all duration-200 bg-black border-2 border-black rounded-lg hover:bg-white hover:text-black"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  width="24"
                  height="24"
                >
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path
                    fill="currentColor"
                    d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"
                  />
                </svg>
              </button>
              <CreateSessionCard
                sessionCard={sessionCard}
                setSessionCard={setSessionCard}
              />
            </div>
            <div className="">
              {sessions && sessions.length !== 0 ? (
                <div>
                  {sessions?.map((session) => (
                    <Link key={session.id} href={`/session/${session.id}`}>
                      <a>
                        <div className="p-6 mb-4 transition-all duration-200 bg-white rounded hover:bg-gray-100">
                          <h4 className="font-bold">{session.class_code}</h4>
                          <h5 className="mb-3 font-medium text-gray-400">
                            {session.name}
                          </h5>
                          <div className="flex items-center space-x-2">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              width="16"
                              height="16"
                            >
                              <path fill="none" d="M0 0h24v24H0z" />
                              <path d="M17 3h4a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4V1h2v2h6V1h2v2zm-2 2H9v2H7V5H4v4h16V5h-3v2h-2V5zm5 6H4v8h16v-8z" />
                            </svg>
                            <h5 className="text-xs font-medium">
                              {new Date(session.startedAt).toLocaleDateString()}
                            </h5>
                            <h5 className="text-xs font-medium">
                              {
                                new Date(session.startedAt)
                                  .toTimeString()
                                  .split(" ")[0]
                              }
                            </h5>
                          </div>
                        </div>
                      </a>
                    </Link>
                  ))}
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center w-full p-6 space-y-2 text-gray-600 bg-white rounded-md min-h-28">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="48"
                    height="48"
                  >
                    <path fill="none" d="M0 0H24V24H0z" />
                    <path
                      // fill="currentColor"
                      d="M21 3c.552 0 1 .448 1 1v14c0 .552-.448 1-1 1H6.455L2 22.5V4c0-.552.448-1 1-1h18zm-1 2H4v13.385L5.763 17H20V5zm-7 2v8h-2V7h2zm4 2v6h-2V9h2zm-8 2v4H7v-4h2z"
                    />
                  </svg>
                  <h4 className="font-bold">No session yet</h4>
                </div>
              )}
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
export default withProtected(Home);
