import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { withProtected } from "../firebase/auth/hook/route";
import Layout from "../layouts/Layout";
import CreateSessionCard from "@/components/CreateSessionCard";
// import useSWR from "swr";
// import fetcher from "@/lib/fetcher";
import { Session } from ".prisma/client";
import useAuth from "../firebase/auth/hook/auth";

function Home() {
  const { user }: any = useAuth();
  const [searchValue, setSearchValue] = useState("");
  const [sessionCard, setSessionCard] = useState(0);
  const [sessions, setSessions] = useState<Session[]>();

  const filteredSessions = sessions
    ?.sort(
      (a, b) => Number(new Date(b.startedAt)) - Number(new Date(a.startedAt))
    )
    .filter((session) =>
      session.class_code.toLowerCase().includes(searchValue.toLowerCase())
    );

  useEffect(() => {
    const fetchSessions = async () => {
      const fetcher = await fetch("/api/db/session/get", {
        method: "POST",
        body: JSON.stringify({ email: user.email }),
        headers: {
          "Content-Type": "application/json",
        },
      });
      const result = await fetcher.json();
      setSessions(result.session);
    };
    fetchSessions();
  }, [user.email]);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className="mb-7">Dashboard</h2>

        <div className="w-full mt-10">
          <div className="w-full">
            <div className="flex mb-5">
              <h3 className="w-full font-bold">Session</h3>
            </div>
            <div className="flex mb-10">
              <input
                type="text"
                className="w-full px-4 py-2 mr-4 transition-all duration-200 border rounded-lg hover:bg-gray-100 focus:bg-gray-100"
                placeholder="Search"
                onChange={(e) => setSearchValue(e.target.value)}
              />
              <button
                onClick={() => setSessionCard(1)}
                className="px-4 py-2 text-white transition-all duration-200 bg-black border-2 border-black rounded-lg hover:bg-white hover:text-black"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  width="24"
                  height="24"
                >
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path
                    fill="currentColor"
                    d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"
                  />
                </svg>
              </button>
              <CreateSessionCard
                sessionCard={sessionCard}
                setSessionCard={setSessionCard}
              />
            </div>
            <div className="">
              {filteredSessions && filteredSessions.length !== 0 ? (
                <div>
                  {filteredSessions?.map((session) => (
                    <Link key={session.id} href={`/session/${session.id}`}>
                      <a>
                        <div className="p-6 mb-4 transition-all duration-200 bg-white rounded hover:bg-gray-100">
                          <h4 className="font-bold">{session.class_code}</h4>
                          <h5 className="mb-3 font-medium text-gray-400">
                            {session.name}
                          </h5>
                          <div className="flex items-center space-x-2">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              width="16"
                              height="16"
                            >
                              <path fill="none" d="M0 0h24v24H0z" />
                              <path d="M17 3h4a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4V1h2v2h6V1h2v2zm-2 2H9v2H7V5H4v4h16V5h-3v2h-2V5zm5 6H4v8h16v-8z" />
                            </svg>
                            <h5 className="text-xs font-medium">
                              {new Date(session.startedAt).toLocaleDateString()}
                            </h5>
                            <h5 className="text-xs font-medium">
                              {
                                new Date(session.startedAt)
                                  .toTimeString()
                                  .split(" ")[0]
                              }
                            </h5>
                          </div>
                        </div>
                      </a>
                    </Link>
                  ))}
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center w-full p-6 space-y-2 text-gray-600 bg-white rounded-md min-h-28">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="48"
                    height="48"
                  >
                    <path fill="none" d="M0 0H24V24H0z" />
                    <path
                      // fill="currentColor"
                      d="M21 3c.552 0 1 .448 1 1v14c0 .552-.448 1-1 1H6.455L2 22.5V4c0-.552.448-1 1-1h18zm-1 2H4v13.385L5.763 17H20V5zm-7 2v8h-2V7h2zm4 2v6h-2V9h2zm-8 2v4H7v-4h2z"
                    />
                  </svg>
                  <h4 className="font-bold">No session yet</h4>
                </div>
              )}
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
export default withProtected(Home);
